### ISSUE TITLE
New border preview

### ISSUE THREAD

**Issue by memmam** [placeAtlas/atlas#1020]
A way is needed for volunteers to preview borders for new/edited entries before merging them in to the main repo; as it is a lot of entries are getting in whose purpose is to grief art pieces by covering them up with false borders, see [this](https://media.discordapp.net/attachments/961679684259680316/961679693273247764/unknown.png) example of people griefing the alliance between Israel and Mega Man as well as multiple of their neighbors.

**Comment by Wayland-Smithy** [comment]
Can you elaborate a little more on what you mean? For submissions/edits that are PRed you can look at the deployment preview. It just becomes a chore when there are hundreds at a time because you have to look for each one individually among the rest unless you clone the repo and put only the new ones in `atlas.json`

**Comment by nico-abram** [comment]
I think the previews are new now that netlify gave us free resources. The netlify deployments used to be disabled on PRs into cleanup iirc.

Maybe this can be closed now that they are working?

**Comment by Wayland-Smithy** [comment]
@nico-abram You are correct. Looks like the PRs into the cleanup branch do not preview as of now, so that would be nice to get working. At least we have it for the large reddit submission ones targeting master.

Still does not help that it's very tedious to check all the new ids by hand. Best of both worlds would be previews enabled for cleanup branch and a different boarder color for new entries. That latter bit sounds like a task and a half to implement though so I'm not holding my breath. Probably would need a totally separate "diff" preview and that's double the resources etc.. Actually might be doable if CORS plays nice and you can subtract the live JSON from the preview 🤔

**Comment by nico-abram** [comment]
I was thinking of getting such a "diff view" for the reddit submissions, to make moderating them easier. If/When that's done, maybe a github bot that generates a diffview of PRs could be done, but that's honestly quite a bit of work

**Comment by Wayland-Smithy** [comment]
For sure anything we can put out akin to a "diff view" could be really helpful. Will @ you if I'm able to come up with something that isn't too complex for its own good.

Some good news: deployment previews are now being made for the cleanup branch PRs. They might have been all along and just no comment was posted not sure, but one could find out by editing the URL numbers I suppose.
