### ISSUE TITLE
Other potential alternatives

### ISSUE THREAD

**Issue by Codixer** [placeAtlas/atlas#1319]

**Comment by Hans5958** [comment]
Since Stefan click that tiny little issue icon, let's fill something here.

Here are some canvas where we can use for the alternatives.

- [Denoised Final Image/Last Hour Average by u/scaevolus](https://www.reddit.com/r/place/comments/tx3w5f/rplace_denoised_final_image_8k/)
- [Last Hour Median by u/DavidXGA](https://www.reddit.com/r/place/comments/tx7q9z/i_took_the_median_value_of_every_pixel_in_the/)
- TBA

**Comment by Hans5958** [comment]
But, the true question: Should we add them?

**Comment by Squizie3** [comment]
No strong opinion on whether to include them or not. It's probably doable since there's already a drop down for the final clean version now.

But I feel like there might be a difference between the final clean version, which was another community effort on its own, and some other hand cleaned versions which are more a single individual's vision on the same task. Then there's also the 'averaged over xx time' versions, which are yet another category. Including one or two of those has more value than adding another series of individual's own hand cleaned versions IMO.

For the time averaged versions, I found this interesting one: [Average pixel color of every pixel on the canvas during the whole event](https://www.reddit.com/r/place/comments/tx14va/i_made_an_image_of_the_average_pixel_color_of/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

**Comment by Hans5958** [comment]
I have created https://github.com/Hans5958/place-catalog, which is a fork of mine that includes all of the mentioned variations/alternatives. This can be closed, but I will keep this opened until the remaster got merged.
