### ISSUE TITLE
Bottom layer of pixels all black - incorrect

### ISSUE THREAD

**Issue by SkyyWasTaken** [placeAtlas/atlas#1325]
Howdy. The 2022 Atlas is rendering all black pixels at the very bottom of the image rather than the actual pixels in the image.

Browser: Firefox

Source: trust me bro

**Comment by Hans5958** [comment]
I don't think this is happening. I think this is because the black pixels are resulted from the entry border. If you use the Explore mode and use Inspect Element, you would see the border of the bottom image, and it is not all black.

![image](https://user-images.githubusercontent.com/11584103/164965265-e5d83078-bd73-4bc1-b29c-ca0c17969875.png)
