### ISSUE TITLE
Why did my PR get closed with SUBMIT ON REDDIT?

### ISSUE THREAD

**Issue by ab-gh** [placeAtlas/atlas#396]
We received far too many PRs on the repo, and we changed the way the data is stored. Sorry!

Please submit your contribution [to the subreddit](https://www.reddit.com/r/placeAtlas2/comments/tu203o/how_to_contribute/)

**Comment by Razr39325** [comment]
But I already have submitted my pr through the subreddit too since the reddit post said to make a post on the subreddit with the pr link (at least, that's what I remember before it got edited).
What will happen if you come across an entry that covers the same area? Will it be ignored on a first come first serve basis?
Should I open a new pr with a new reddit post with the flair of "Edit Entry"?

**Comment by VortexParadox** [comment]
The atlas website also still points to using GH for submissions

**Comment by birdbrainswagtrain** [comment]
Seems like a weird decision, especially considering some of the [JSON is getting mangled.](https://github.com/Codixer/place-atlas/issues/410) Reddit isn't exactly well regarded as a ticketing system.

**Comment by memmam** [comment]
@birdbrainswagtrain From what I've heard, new entry requests on the subreddit are regularly scraped by a bot, this is just a guess on my part but the separation between new entries on Reddit and entry edit PRs on GitHub is likely to keep new and edit requests somewhat separate so they can be handled separately.

**Comment by ipatrol** [comment]
Have you considered separating the atlas data as a JSON file from the js file it's currently contained in?

**Comment by memmam** [comment]
@ipatrol I don't understand, the atlas data IS in a JSON file. That's how I've been making my edits.

it's at /web/atlas.json
