### ISSUE TITLE
My pull request says it's merged, but it hasn't made it to the main cleanup branch people are currently forking from. 

### ISSUE THREAD

**Issue by Chtlotl** [placeAtlas/atlas#806]
All of my committed changes appear to have reverted. 

https://github.com/placeAtlas/atlas/pull/677

**Comment by TrevorSayre** [comment]
It looks like your pull request included major formatting changes to `atlas.json`. Your best bet is probably to open a new Pull Request and make sure the diff doesn't look like this:
![image](https://user-images.githubusercontent.com/421548/162051824-5fea3360-891f-449c-b6ab-36a619fc5776.png)

but more like this:
![image](https://user-images.githubusercontent.com/421548/162051845-e373724b-479d-4539-927f-abdc269f9539.png)

(with your changes, not mine, of course)

**Comment by nico-abram** [comment]
This commit in your PR https://github.com/placeAtlas/atlas/pull/677/commits/cf2309848e10c0443a44e52f977767228ae36425

Added a completely new Atlas.json (**not** atlas.json)

It was deleted ASAP because it was giving some of us with case insensitive file systems a lot of trouble. You'll have to send your changes again in a new PR. Sorry, we should have caught that in review
